version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meetingroom-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: meetingroom
      POSTGRES_USER: byeongdoohan
      POSTGRES_PASSWORD: p@ssw0rd
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U byeongdoohan -d meetingroom"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meetingroom-app
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://meetingroom-postgres:5432/meetingroom
      SPRING_DATASOURCE_USERNAME: byeongdoohan
      SPRING_DATASOURCE_PASSWORD: p@ssw0rd
    volumes:
      - ./logs:/app/logs  # Optional: for persistent logs

volumes:
  pgdata: