spring:
  application:
    name: meetingroom
  data:
    redis:
      port: 6379
      host: meetingroom-redis
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /api-docs

logging:
  level:
    com.example.meeting-room: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
jwt:
  access-token-validity-in-seconds: 3600
  refresh-token-validity-in-seconds: 86400
