spring:
  application:
    name: meetingroom
springdoc:
  swagger-ui:
    path: /docs
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /api-docs

logging:
  level:
    com.example.meeting-room: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE