name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # Ubuntu 최신 버전 러너 사용

    steps:
    - uses: actions/checkout@v3 # 저장소 코드 체크아웃

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17' # Java 17 사용
        distribution: 'temurin' # Temurin 배포판 사용

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew # gradlew 실행 권한 부여

    - name: Build with Gradle
      run: ./gradlew clean build # Gradle을 사용하여 프로젝트 빌드 및 테스트 실행

    # (선택 사항) Docker 이미지 빌드 및 푸시 단계 추가 가능
    # - name: Build Docker image
    #   run: docker build -t your-docker-repo/your-app:latest .
    # - name: Log in to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    # - name: Push Docker image
    #   run: docker push your-docker-repo/your-app:latest
